### ISSUE TITLE
Negative altitude causes sunset/rise times to be incorrect

### ISSUE THREAD

**Issue by hardiesoft** [Eroc33/sun-times#2]
I had some location which was at `-3.7812186e-32` meters below sea level, which caused the returned date times to be out by many hours.  I was able to "fix" it by doing `val.max(0.0)` on the altitude, which I think is probably a good enough solution for most people, since you don't really expect sunset/sunrise times at elevations below sea level.

**Comment by Eroc33** [comment]
Thanks for the bug report. Sorry it took so long for me to get back to you, I haven't been very well over the past year or so.

I'm suprised you don't just get `NaN` from a negative elevation.
I think setting the elevation to 0 if you are below sea level is the correct thing to do, as it's trying to account for atmospheric refraction, which should be minimal at negative elevations.

I've published 0.2.0, which does this clamping in the calculation, and also adds a note to the doc comment
